name: Check CLA
on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  check-contributors:
    env:
      GLOBAL_MSG: "Original message with XX to replace"
    runs-on: ubuntu-latest
    steps:
      - name: Clone CONTRIBUTORS
        uses: actions/checkout@v2.3.4
        with:
          repository: ockam-network/contributors
          path: contributors

      - name: Check CONTRIBUTORS
        run: |
          whoami
          pwd
          ls -l contributors/
          grep sobi3ch contributors/CONTRIBUTORS.csv
          grep sobi3ch contributors/CONTRIBUTORS.csv | cut -d',' -f1
          OUTPUT=$(echo $GLOBAL_MSG | sed 's#XX#SOMTHING#g')
          echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV

      - name: Add comment CLA
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'Ockam[bot]' # The user.login for temporary GitHub tokens
          message: |
            Thank you ${{ github.event.pull_request.user.login }} for creating this PR. Please sign your CLA.
            Overwrite GLOBAL message: ${{ env.MESSAGE }}

      # - name: Add PR comment
      #   if: github.event_name == 'pull_request'
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     body: |
      #       Thank you ${{ github.event.pull_request.user.login }} for creating your this PR. Please sign your CLA.

      - name: Add ISSUE comment
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you ${{ github.event.issue.user.login }} for creating this issue. Before you continue you will need to sign our CLA.
            To do it please create a new PR to the https://github.com/ockam-network/contributors repo adding yourself to the CSV file.
            Overwrite GLOBAL message: ${{ env.MESSAGE }}
