name: Check CLA
on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  check-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment PR
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'Ockam[bot]' # The user.login for temporary GitHub tokens
          message: |
            Thank you ${{ github.event.pull_request.user.login }} for creating your ${{ github.event.action }}. Please sign your CLA.
            event name: ${{ github.event_name }}

      - name: Add ISSUE comment
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you ${{ github.event.pull_request.user.login }} for creating your ${{ github.event_name }}. Please sign your CLA.
