name: Check CLA
on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  check-contributors:
    env:
      GLOBAL_MSG: "Message with XX to replace"
    runs-on: ubuntu-latest
    steps:
      - name: Check CONTRIBUTORS
        uses: actions/checkout@v2.3.4
        with:
          name: ockam-network/contributors
          path: contributors
        run: |
          ls -l contributors/CONTRIBUTORS.csv
          grep sobi3ch contributors/CONTRIBUTORS.csv
          grep sobi3ch contributors/CONTRIBUTORS.csv | cut -d',' -f1

      - name: Add comment CLA
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'Ockam[bot]' # The user.login for temporary GitHub tokens
          message: |
            Thank you ${{ github.event.pull_request.user.login }} for creating this PR. Please sign your CLA.

      # - name: Add PR comment
      #   if: github.event_name == 'pull_request'
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     body: |
      #       Thank you ${{ github.event.pull_request.user.login }} for creating your this PR. Please sign your CLA.

      - name: Add ISSUE comment
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you ${{ github.event.issue.user.login }} for creating your this issue. Please sign your CLA.
