name: Check CLA
on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  check-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          name: ockam-network/contributors
          path: contributors
        run: |
          ls -l contributors/CONTRIBUTORS.csv
          grep sobi3ch contributors/CONTRIBUTORS.csv
          grep sobi3ch contributors/CONTRIBUTORS.csv | cut -d',' -f1
      - name: Add comment CLA
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'Ockam[bot]' # The user.login for temporary GitHub tokens
          message: |
            Thank you ${{ github.event.pull_request.user.login }} for creating your ${{ github.event.action }}. Please sign your CLA.
            event name: ${{ github.event_name }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you ${{ github.event.pull_request.user.login }} for creating your ${{ github.event_name }}. Please sign your CLA.
