name: Check CLA
on:
  issues:
    types: [opened, edited, milestoned]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  check-contributors:
    env:
      GLOBAL_MSG: "Thank you {0} for creating your this {1}. Please sign your CLA."
    runs-on: ubuntu-latest
    steps:
      # - name: Add comment PR
      #   if: github.event_name == 'pull_request'
      #   uses: mshick/add-pr-comment@v1
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     repo-token-user-login: 'Ockam[bot]' # The user.login for temporary GitHub tokens
      #     message: |
      #       Thank you ${{ github.event.pull_request.user.login }} for creating this PR. Please sign your CLA.
      #       global message: ${{ env.GLOBAL_MSG }}

      - name: Add PR comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            Thank you ${{ github.event.pull_request.user.login }} for creating your this PR. Please sign your CLA.
            global message: ${{ env.GLOBAL_MSG }}

      - name: Add ISSUE comment
        if: github.event_name == 'issues'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ format(${{ env.GLOBAL_MSG }}, ${{ github.event.issue.user.login }}, 'issue') }}
